version: '3.5'

volumes:
  postgres_data:
    driver: local

services:
  postgres_cadastro:
    container_name: postgres_hearthstone
    image: postgres
    volumes:
      - postgres_data:/var/lib/mysql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"